rails-web-dev-book/demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

rails-web-dev-book/demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @name = "Charlie"    
  end

  def goodbye
    @files = Dir.glob('*')
  end
end

rails-web-dev-book/demo/app/helpers/say_helper.rb
module SayHelper
end

rails-web-dev-book/demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-web-dev-book/demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
It was nice having you here.
</p>
<p>Say <%= link_to "Hello", say_hello_path %></p>
<ul>
<% @files.each do |file| %>
    <li><%= file %></li>
<% end %>
</ul>

rails-web-dev-book/demo/app/views/say/hello.html.erb
<h1>Hello, <%= @name %>...</h1>
<p>The time is <%= @time %>.</p>
<p>Time to say
 <%= link_to "Goodbye", say_goodbye_path %>!
</p>
<h2>This is cool <%= 1 + 2  %> <%= "cow" + "boy" %> <%= 1.hour.from_now.localtime %></h2>
<pre>I am weird text</pre>